[점심 뭐 먹지 미션 Step 2] 도담(김민재) 미션 제출합니다.
woowacourse/react-lunch pull request #49
Opened 2023-04-14 08:17 UTC by D0Dam

동동~! 질문을 많이 남겼는데 모두 자세하게 설명해 주셔서 너무 고마워요~!!!
step2에서는 함수형 컴포넌트로 바꾸는 과정이 메인이어서 큰 변경사항은 마이그레이션 말고는 없지만 다음과 같은 내용이 바뀌었어요~!

## 바뀐 내용
- 컴포넌트를 함수형으로 변경하였습니다.
- useContext를 추가적으로 사용하였습니다.
- noscript, prettier 명령어 등 작은 피드백을 반영하였습니다.
- 모달에서 음식점이 undefined가 뜨는 문제를 수정하였습니다.
- 아래의 두 함수를 utils로 분리하였습니다.
  - 카테고리 이름에 따라 아이콘을 가지고 오는 함수
  - 카테고리와 정렬방식을 받아 음식점을 정렬, 필터하는 함수

이번에는 크게... 궁금한점을 찾지는 못했어요! 월요일까지 빠르게 피드백 받아야해서 최대한 빠르게 PR 보내봅니다~!

2023-04-14 17:13 UTC, bigsaigon333 requested changes
도담 안녕하세요~

빠르게 2단계를 구현하셨군요!

이제 리액트 + TS + 함수형 컴포넌트 쓰니까 이제 좀 안구가 정화가 되네요 😂😂

진정한(?) 프론트엔드 세계에 오신걸 환영합니다 🎉🎉

리뷰는 코멘트 확인해주세요~

2023-04-14 17:13 UTC, bigsaigon333 commented on package.json
> +		"prettier": "prettier --write ./src/**/*.{ts,tsx,css,html,json}"
```suggestion
		"prettier": "prettier --write --ignore-unknown ."
```

prettier가 적용가능한 모든 파일에 적용시켜버리는 방법도 있습니다 ㅎㅎ..

2023-04-14 17:13 UTC, bigsaigon333 commented on public/index.html
> +    <noscript>Put Sample code here for execution when JavaScript is Disabled</noscript>
멘트는 적당히 바꾸시는게 좋지 않으까요?!

2023-04-14 17:13 UTC, bigsaigon333 commented on src/components/RestaurantList/index.tsx
> +import React, { useContext } from 'react';
```suggestion
import { useContext } from 'react';
```

다른  파일도 모두 마찬가지인데, `React`가 이제 안쓰이니까 import 안써도 되지 않을까요?

2023-04-14 17:13 UTC, bigsaigon333 commented on src/styles/reset.css
> +
https://github.com/woowacourse/react-lunch/pull/12#discussion_r1166262553

2023-04-14 17:13 UTC, bigsaigon333 commented on src/store.ts
> +const Store = React.createContext<State>({} as State);
{}가 State가 아님에도 불구하고 State라고 거짓말을 하는건 타입시스템 전반에 대한 신뢰도를 떨어트립니다. 

이런게 쌓이게 되면, 정말 이 타입이 런타임에도 동일한 타입을 가지고 있는걸까? 라는 의구심이 쌓이게 됩니다.

context에서 자주 쓰이는 패턴이 있는데, 어떻게 하면 좋을지 조금더 고민해보세요 😄 (관련 블로그 글들도 꽤 많습니다)

2023-04-14 17:13 UTC, bigsaigon333 commented on src/App.tsx
> +	);
hook이 등장할 타임이군요.

App 컴포넌트와 category 등등의 상태들이 관련이 있을까요 아니면 Store 컨텍스트와 관련이 있을까요?

관련 있는 것들을 모아서 응집도 있게 만들어봅시다!

1단계 PR에서도 질문하셨떤거 같은데 상태가 비대하게 느껴진다면, 정말 다 관련이 있는 것들인가를 한번 생각해보세요. 

필요하다면 Context API를 여러개 쓰는 것도 나쁘지 않습니다. 응집도 있게 모으는게 훨~~씬 중요합니다

2023-04-15 09:39 UTC, D0Dam commented on package.json
> +		"prettier": "prettier --write ./src/**/*.{ts,tsx,css,html,json}"
!! 그런 방법도 있군요..ㅎㅎ
아직 이쪽(package.json) 스크립트를 작성하는 방법이나 prettier, lint 에서 제공하는 명령어를 잘 몰라서 그냥 쉽게쉽게 넘어갔는데, 시간이 되면 이 쪽도 좀 찾아볼 필요가 있겠어요 : )

2023-04-15 09:40 UTC, D0Dam commented on public/index.html
> +    <noscript>Put Sample code here for execution when JavaScript is Disabled</noscript>
앗! ㅎㅎ.. 생각없이 그냥 가져온게 너무 드러난 것 같은 기분인걸요🫠

이번 기회에 다들 noscript를 어떤 식으로 작성하는지 알아보고 제가 작성해볼게요~!

2023-04-15 09:41 UTC, D0Dam commented on src/components/RestaurantList/index.tsx
> +import React, { useContext } from 'react';
ㅠㅜㅜ 호다닥 해서 그런가 이런 부분들을 놓친 게 많네요..
잡아주셔서 감사합니다~!

2023-04-15 09:46 UTC, D0Dam commented on src/store.ts
> +const Store = React.createContext<State>({} as State);
네..! 찾아보고 적용해서 다음 리뷰 때 추가적으로 느낀 점을 남겨볼게요~!

2023-04-15 09:51 UTC, D0Dam commented on src/App.tsx
> +	);
사실 저도 그 부분을 생각해 보았는데요...
기존 제 생각으로는 상태를 같이 공유해야 하는 컴포넌트가 음식점 모달, 카테고리 select박스, 음식점 목록 이렇게더라구요..
그래서 이 3개를 묶어보았는데 이 3개 컴포넌트가 모두 App.tsx에 빠져 있어서 다음과 같은 구조가 된 것 같습니다!
이번 리팩토링 동안 이 부분도 고려해서 이걸 쪼개볼 수 있는지, 한 번 다시 생각을 해볼게요!

2023-04-17 08:55 UTC, D0Dam commented
동동~! 수정사항을 정리해서 작성해 보았어요! 참고해주세요~!
(컨텍스트 분리를 열심히 해보고 그랬지만... 여전히 마음에는 안드네요 ㅠㅜ)

## 수정사항 정리
- noscript 켐플릿 추가
- 필요없는 import 제거, 이에 필요한 rule-off, tsconfig 설정 추가
- context null check를 위한 커스텀 훅 추가(useWrappingcontext)
- 모달 데이터를 레스토랑 리스트와 모달간만 공유하도록 음식점 목록 상태를 RestaurantList로 위치 변경
  - 음식점 목록 갱신을 하는 커스텀 훅 추가
- select option 박스 값을 바꾸고 반환하는 커스텀 훅 추가
- modal 관리를 위한 커스텀 훅 추가
- modal 관련 정보를 담는 context store 추가

## 고려한 점
- context 의 null을 검사하기 위해 훅을 구상해 보았습니다! 단지 null check를 위해서 훅으로 분리하는 것이 올바른 판단이었을까요?
- 최대한 기존 상태와 상태 변경에 필요한 로직을 커스텀 훅으로 분리하였습니다!
  - 기존에 훅을 만들 때에는 어느정도 재활용성을 고려했는데, 너무 무분별하게 커스텀 훅으로 리팩토링하지 않았나 싶습니다.
  - 그래서 단순히 로직만 옮겨 놓은 커스텀 훅이 만들어져 오히려 코드를 읽기 불편해 지지 않을까 생각이 들었습니다.
  - 이렇게 커스텀 훅으로 최대한 로직을 빼내는 것이 과연 일종의 패턴이라고 봐도 될까요?
- context에 들어가는 정보를 나누어 카테고리 박스와 모달 정보 각각의 store를 만들어주었습니다.
  - 여전히 카테고리 관련 store는 app.tsx에 존재하기는 합니다만... 이 컨텍스트와 자식간의 깊이가 1밖에 되지 않아 별도의 파일로 분리하지 않는 한 카테고리 관련 store를 app.tsx에서 배제하기는 힘들었습니다. 차라리 별도의 파일로라도 `RestaurantList`와 `SelectorSection`을 묶은 별도의 컴포넌트를 만들어야 했을까요?(저는 이게 불필요하다고 생각해 이대로 두었습니다..)

항상 리뷰를 빨리 남겨주셔서 너무 감사해요! 덕분에 첫 피드백을 알차게 받고 있습니다! : )

2023-04-17 15:27 UTC, bigsaigon333 approved these changes
도담 안녕하세요~

context 관련해서 몇가지 코멘트 더 남겼습니다!

더 수정을 해보아도 좋지만, 다음 미션 진행도 해야하기 때문에

일단 approve 할게요! 

머지는 며칠 뒤에 할테니, 더 리팩토링 하고 싶으시면 시도해보세요 😄 😄 

---

> context 의 null을 검사하기 위해 훅을 구상해 보았습니다! 단지 null check를 위해서 훅으로 분리하는 것이 올바른 판단이었을까요?

네 저는 훌륭하다고 생각합니다~
제가 딱 원했던것도 null check를 넣어서 type-safe 하게 가져가는 것이었고,
한단계 더 나아가 여러 context에서 사용되기 때문에 재사용을 위해 분리해낸 것이 훌륭합니다 👍🏻 👍🏻 👍🏻 

> 최대한 기존 상태와 상태 변경에 필요한 로직을 커스텀 훅으로 분리하였습니다!
> 기존에 훅을 만들 때에는 어느정도 재활용성을 고려했는데, 너무 무분별하게 커스텀 훅으로 리팩토링하지 않았나 싶습니다.
> 그래서 단순히 로직만 옮겨 놓은 커스텀 훅이 만들어져 오히려 코드를 읽기 불편해 지지 않을까 생각이 들었습니다.
> 이렇게 커스텀 훅으로 최대한 로직을 빼내는 것이 과연 일종의 패턴이라고 봐도 될까요?

커스텀 훅은 유틸함수+리액트 라이프사이클입니다. 유틸함수는 최대한 도메인 로직을 담지 않고 하나의 기능만 잘 수행하도록 만들어야 하듯, 커스텀 훅도 똑같습니다.
단순히 컴포넌트가 길어지는게 싫어서 훅으로 분리해낸다면,
컴포넌트를 조금만 변경에도 훅을 수정해야하는 일이 생깁니다. 
그런데, 처음부터 잘 할 수는 없겠쬬. 많이 연습해보세요. 이건 훅으로 분리해낼 수 있을거 같은데? 하면 다 분리해보세요!
컴포넌트에 그냥 다 몰아넣었다가, 이정도면 훅으로 해도 될거 같은데? 라는 소극적 자세보다는
리뷰어가 봐줄 때 다 훅으로 뜯어보자는 마음가짐이 좀더 낫지 않을까 생각합니다 ㅎㅎ..


> context에 들어가는 정보를 나누어 카테고리 박스와 모달 정보 각각의 store를 만들어주었습니다.
> 여전히 카테고리 관련 store는 app.tsx에 존재하기는 합니다만... 이 컨텍스트와 자식간의 깊이가 1밖에 되지 않아 별도의 파일로 분리하지 않는 한 카테고리 관련 store를 app.tsx에서 배제하기는 힘들었습니다. 차라리 별도의 파일로라도 RestaurantList와 SelectorSection을 묶은 별도의 컴포넌트를 만들어야 했을까요?(저는 이게 불필요하다고 생각해 이대로 두었습니다..)

store 나눈거 좋습니다~! app.tsx에 두는 것도 좋습니다~!

다른 관점에서 말씀드리고 싶은건, 
context api를 너무 prop drilling 을 피하는 관점에서만 적용하신거 같아요

useSelector의 반환값을 그냥 SelectorStore.Provider로 주입해줄거라면, 
useSelector 로직과 SelectorStore.Provider 로직을 하나로 합쳐도 충분하지 않을까요??



```tsx
export const SelectorProvider = ({ children }: Props) => {
  const value = useSelector();

  return (
    <SelectorContext.Provider value={value}>
      {children}
    </SelectorContext.Provider>
  );
};


```

2023-04-17 15:27 UTC, bigsaigon333 commented on src/hooks/useWrappingContext.ts
👍🏻 👍🏻 👍🏻 👍🏻 👍🏻

2023-04-17 15:27 UTC, bigsaigon333 commented on src/components/RestaurantList/hooks/useRestaurantList.ts
> +    const resultList = getSortingFilteredList(category, sortOption, mock);
getSortingFilteredList 가 이 hook에서만 사용된다면, 

getSortingFilteredList는 이 hook안에 같이 두는게 좋다고 생각해요.

같이 변경되는 것들은 같은 곳에 위치시킨다: colocation 

https://kentcdodds.com/blog/colocation

colocation 개념이 중요합니다!!

2023-04-17 15:27 UTC, bigsaigon333 commented on src/store.ts
> +export const ModalStore = createContext<ModalState | null>(null);
(궁금) 근데 왜 Store 라는 네이밍을 붙이셨나요?

2023-04-17 15:27 UTC, bigsaigon333 commented on src/store.ts
컨텍스트를 선언하는 곳에서 Provider와 Hook을 같이 선언해서 export 하는 경우도 많이 있습니다~! 
(저희 팀은 99% 그렇게 하고 있씁니다..)

그러면 useContext 를 호출하는 컴포넌트에서는 그냥 다른 Hook과 똑같이 쓰는거죠~

```ts
export const SelectorStore = createContext<SelectorState | null>(null);

export const SelectorProvider = ({ children, value }: Props) => (
  <SelectorStore.Provider value={modalStore}>{children}</SelectorStore.Provider>
);

export const useSelectorStore = () => {
  return useWrappingContext(SelectorStore);
};

```

2023-04-19 01:44 UTC, D0Dam commented
헉! 코드 리뷰 알람이 계속 안와서 조금 늦으시는구나 했었는데 알람이 묻힌 거였군요.. 좀 늦게 확인했습니다.. ㅠㅜㅜ

바꿔보고 싶은 마음이 굴뚝같은데 이번 새로운 페어의 목요일 예비군 이슈로... 오늘은 사알짝.. 제쳐 두겠습니다! 😂
하게 되면 목요일날 좀 더 리팩토링을 진행해볼게요~!

2023-04-23 10:19 UTC, merged