[점심 뭐 먹지 미션 Step 2] 엽토(김건엽) 미션 제출합니다.
woowacourse/react-lunch pull request #56
Opened 2023-04-15 11:16 UTC by yeopto

안녕하세요 케빈!

step2 요구사항은 함수형 컴포넌트로 마이그레이션 하는거였어요!

기존 클래스 컴포넌트에 사용하였던 상태관리는 useState를 사용하고 생명주기 메서드로 관리되었던 로직들은 useEffect로 관리했습니다.

요구사항 중 Custom Hooks를 이용하여 재사용가능한 기능들을 분리해본다란 요구사항이 있었는데, 제가 아직 리액트에 익숙하지 않아서 어떤 부분을 Hooks로 분리해야할지 감이 안오더라구요.. 분리할게 있을까란 생각도 들고요!
Custom Hook과 관련된 tip과 리뷰를 해주시면 정말 감사하겠습니다!

피드백 주신 버튼 태그 타입 명시, 비구조화 할당은 반영하였습니다!

그럼 step1에서 주신 질문에 대한 제 생각을 써보겠습니다!

> 추가로 지금 엽토가 리액트 작업을 하면서 여러 컴포넌트로 나눠 주셨는데, 엽토만의 컴포넌트 기준이 있을까요?

- 사실 아직 정확하게 설명할 수 있는 기준을 잡고 있지는 않은 것 같아요! 약간 감으로 구성해보는 것 같습니다..!
- 저는 일단 레이아웃 구조를 탑다운으로 잡아봅니다. Header, Main, Footer를 생각하고 각 컴포넌트엔 어떠한 자식 컴포넌트가 필요할 지 위에서 아래로 내려가면서 구조를 생각해봅니다. 다음으로는 레이아웃을 잡은 다음에 상태를 어디서 관리하여 props로 내려줄지 생각을 해봅니다. 이 단계에서 컴포넌트 구조를 바꿔보기도 합니다! 그런 뒤 공통되는 것들이 있으면 하나의 컴포넌트로 만들어줘보기도 합니다(이번 미션에서는 Filter 컴포넌트가 되겠네요)
- 이런식으로 컴포넌트들을 만들어 갑니다! 이게 저만의 기준이라고 말하기엔 뭔가 명확하지가 않은 것 같네요! 

> css 의 네이밍을 가져와서 className 을 사용하는게 낯설게 느껴지는데 혹시 이러한 방법을 선택하신 이유가 있으실까요? 오타 방지 및 휴먼 에러 방지를 위해서 일까요?

- 이 말씀을 이해하지 못했습니다 😓 
- CSS Module 방식을 사용하다보니 className에 제가 지정한 스타일 클래스를 넣어주었습니다..!

> 이부분은 놓치기 쉬울 수 있는데, 컴포넌트가 제거될때 componentWillUnmount 시점에 제거해준 이유가 있을까요?

- Modal을 조건부 렌더링하는데 isModalOpen이 true일때는 Mount가 되기때문에 Mount시에 이벤트를 달아주고, isModalOpen의 상태가 false로 변경되면 re-render가 일어나면서 Modal이 unMount가 되기때문에 unMount시 실행되는 라이프사이클메서드인 componentWillUnmount에 이벤트를 제거하는 로직을 작성했습니다! 모달이 닫힌 상태에서는 keyDown 이벤트가 동작하면 안되니까요!

> 리액트를 처음 사용한 맛보기 미션이었을텐데, 어떠셨는지 궁금합니다!
맛보기 미션이니 만큼 첫 리뷰는 가볍고, 안맵게.. 하라는 얘기가 있어서 가볍게 했는데 어떠셨는지 잘 모르겠네요. 🤔

- 이건 DM으로 주신 질문인데요! 1단계 PR메세지에서 말씀드렸지만.. 삽질을 좀 해서 약간 괴롭긴했어요 ㅎㅎ 하지만 바닐라 JS보다는 훨씬 코드도 간결해지고 덜 복잡해지는 것 같았어요! 1단계에서 렌더링 최적화와 관련된 좋은 자료를 주셔서 참 좋았습니다! 제가 삽질한 것에 대한 내용이었으니까요!

저의 답변은 이정도가 되겠습니다!
이번에도 리뷰 잘 부탁드립니다 케빈!

2023-04-16 09:56 UTC, JeongBin0227 commented
> 추가로 지금 엽토가 리액트 작업을 하면서 여러 컴포넌트로 나눠 주셨는데, 엽토만의 컴포넌트 기준이 있을까요?

개인적으로 프론트엔드 개발자가 개발을 하다보면 가장 중요한 개념이 몇몇가지 있는데, 그중에 하나가 컴포넌트라고 생각합니다. 앞으로 엽토가 개발을 하다보면 수많은 컴포넌트를 만들게 될텐데 그럴때마다 어떤걸 컴포넌트로 만들지, 어떤식으로 만들지 기준을 잡으면 좋을거 같아요.
시간이 나실때, 컴포넌트에 대해 많은 고민을 해보면 좋을거같아요!
추가로 본인만의 명확한 기준이 있고, 그걸 잘 얘기할수있다면 나중에 면접에서도 큰 이점으로 작용할거예요~

2023-04-16 09:59 UTC, JeongBin0227 commented
> css 의 네이밍을 가져와서 className 을 사용하는게 낯설게 느껴지는데 혹시 이러한 방법을 선택하신 이유가 있으실까요? 오타 방지 및 휴먼 에러 방지를 위해서 일까요?

이렇게 여쭈어 본 이유가, 보통 다른분들 코드 보면 단순 string 의 classname 을 넣는 경우가 많은데, 이렇게 css 모듈을 사용해서 좋은거 같다고 말씀드리고 싶었습니다!
이렇게 사용하면 css 모듈로 만들어진 결과물을 보시면 알겠지만, 클래스 이름에 대하여 고유한 이름들이 만들어지기 때문에, 실수로 CSS 클래스 이름이 다른 관계 없는 곳에서 사용한 CSS 클래스 이름과 중복되는 일에 대하여 걱정 할 필요가 없습니다.

2023-04-16 10:12 UTC, JeongBin0227 commented
> 어떤 부분을 Hooks로 분리해야할지 감이 안오더라구요..

이미 공부하셨겠지만, 우선 커스텀 hook이 왜 생겨 났는지부터 아시면 좋을거 같아요.
간단하게 말씀드리면, function component에서 hook을 사용함으로 인해 class component 없이도 useState, useEffect 등을 통해 여러 state 값을 변경해줄 수 있게 되었습니다. 

자세한건 공식 문서를 읽어주세요 
https://ko.reactjs.org/docs/hooks-intro.html

2023-04-16 10:21 UTC, JeongBin0227 requested changes
안녕하세요 엽토~
빠르게 올려주셔서 저도 좀더 자세히 볼 수 있었던거 같아요! 💯 

엽토가 질문해 주신 부분이나, 상세 코드, 코드 구조등은 코멘트로 남겨드렸으니, 코멘트 확인해주시면 감사합니다~ 
언제든지 궁금한건 코멘트로 알려주세요~ 이번미션도 고생많으셨습니다 💪

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/Modal/Modal.tsx
> +  });
useEffect 가 class 형태에서 어떤 생명주기에 속하는지 항상 기억해두시면 편합니다~
class 형태에서 2가지의 생명주기를 담고 있어요!

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/RestaurantItem/RestaurantItem.tsx
> +  const { category, name, distance, description } = props;
👍👍👍

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/Main/Main.tsx
> +const Main = () => {
Main 보다 좀더 구체적인 이름으로 하면 어떨까요?
만약 새로운 큰 피쳐가 등장하거나, 지금 수준의 크기에 같은 계층에서 작업할때 App은 모호한 이름이 될 수 있을거 같아요

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/Main/Main.tsx
> +  });
state 를 따로따로 관리해보면 어떨까요? 이유는 밑에 적어둘게요!

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/Main/Main.tsx
> +    setState(prevState => ({ ...prevState, isModalOpen: false }));
현재 state 를 한꺼번에 두고 관리하고 있기 때문에 `{ ...prevState,` 새로운 상태가 추가될때마다 이런 작업을 해줘야하는데, 따로 분리하면 이런것들이 간편해 질거 같아요!

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/Main/Main.tsx
> +  });
하나의 상태가 추가되면 다른 상태에도 영향을 줄수있는 형태로 유지 보수 및 에러에 취약할거 같아요

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/Main/Main.tsx
> +  });
추가로 처음 `restaurantId: undefined`가 undefined를 활용하여 어떤걸 하지 않는다면, undefined 값보다는 실제 타입으로 명시해주면 어떨까요?
ex) 숫자면 0, 스트링이면 ''

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/Main/Main.tsx
> +const Main = () => {
해당 컴포넌트안에, RestaurantFilter 와 RestaurantsList 가 있으니, Restaurants 로 바꿔도 좋겠네요

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/RestaurantFilter/RestaurantFilter.tsx
> +    props.onSortingChange(e.target.value);
이 부분도 상단에서 비구조화할당으로 두면 어떨까요?

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/RestaurantFilter/RestaurantFilter.tsx
> +    props.onCategoryChange(e.target.value);
이 부분도 상단에서 비구조화할당으로 두면 어떨까요?

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/RestaurantFilter/RestaurantFilter.tsx
> +const RestaurantFilter = (props: RestaurantFilterProps) => {
여기 하위에다가 cosnt {onCategoryChange, onSortingChange} ~~ 로 바로 두면 좋겠네요

2023-04-16 10:21 UTC, JeongBin0227 commented on src/components/RestaurantsList/RestaurantsList.tsx
> +      </li>
`restaurantItems` 함수는 이 파일이 아니라 RestaurantItem 파일에 있어야지 좀더 어색하지 않은 형식인거 같아요!

2023-04-17 08:51 UTC, yeopto commented on src/components/Main/Main.tsx
> +const Main = () => {
반영했습니다!

2023-04-17 08:52 UTC, yeopto commented on src/components/Main/Main.tsx
> +  });
따로 관리 해주었고, restaurantId 초기값은 0으로 해줬어요!

2023-04-17 08:52 UTC, yeopto commented on src/components/RestaurantFilter/RestaurantFilter.tsx
> +    props.onSortingChange(e.target.value);
반영했습니다!

2023-04-17 08:53 UTC, yeopto commented on src/components/RestaurantFilter/RestaurantFilter.tsx
> +    props.onCategoryChange(e.target.value);
반영했습니다!

2023-04-17 08:53 UTC, yeopto commented on src/components/RestaurantFilter/RestaurantFilter.tsx
> +const RestaurantFilter = (props: RestaurantFilterProps) => {
반영했습니다!

2023-04-17 09:01 UTC, yeopto commented on src/components/RestaurantsList/RestaurantsList.tsx
> +      </li>
`restaurantItems`는 각 'RestaurantItem' 컴포넌트가 'li' 태그를 부모로 갖고 있도록 만들어주기위해 만든 배열입니다! 이것을 'ul' 태그에 넣기 위해 RestaurantsList에서 해준겁니다!

2023-04-17 09:16 UTC, yeopto commented
케빈! 피드백 주신 것들을 반영해봤습니다!
반영한 부분에 대해서는 코멘트에 남겼습니다!

추가로 TS도 일정 부분 리팩터링 해봤습니다!
그리고 useFilterOptions, useModal등 Custom Hook도 만들어 봤어요!

컴포넌트의 기준에 대해서도 고민해보았습니다.

지금까지 제가 만들어온 컴포넌트들을 생각해봤을 때, 저는 컴포넌트 별로 단일 책임을 가지도록 하는걸 가장 중요시하는 것 같아요! 그 기준으로 분리를 하고 나서 재사용성을 고민하는 것 같습니다! 그 다음이 렌더링 효율성을 생각해보는 것 같아요!

아직 경험이 부족해서 기준이 명확히 안 세워지는 것 같습니다! 하지만 이렇게 미션을 하나씩 해나가면서 피드백을 받다보면 자연스럽게 기준이 잡히지 않을까 싶습니다!

이번에도 많이 배웠습니다 케빈 감사합니다!

2023-04-18 07:24 UTC, JeongBin0227 commented on src/components/Main/Main.tsx
> +  });
아하 그러면 `restaurantId: undefined,` 요기도 같이 반영되면 좋을거같아요~

2023-04-18 08:00 UTC, JeongBin0227 approved these changes
안녕하세요 엽토!
리뷰 반영해주신 최종 코드랑 이전 코드 비교해보니 확실히 더 눈에 잘 들어오고 가독성이 좋아진거 같아요!
그만큼 엽토가 고민도 많이 해주시고 리팩토링도 잘 해주셔서 인거 같아요!

이번 스텝은 여기서 머지하도록 하겠습니다! 👍 다소 많은 리뷰일수도 있었는데 잘 반영해주셔 감사합니다 💯 
고생하셨습니다~

2023-04-18 08:01 UTC, merged

2023-04-25 02:44 UTC, jeongwusi commented on src/components/RestaurantItem/RestaurantItem.tsx
> +  const { category, name, distance, description } = props;
👍🏻👍🏻👍🏻

2023-04-25 02:52 UTC, jeongwusi commented on src/components/Modal/Modal.tsx
> +const Modal = (props: ModalProps) => {
그냥 `Modal`이라고 하면 순수한 모달 컴포넌트를 의미하는지 알 수 없으니... 컴포넌트의 이름을 바꾸면 어떨까욤? ㅎㅎ

2023-04-25 03:13 UTC, jeongwusi reviewed
굿굿

2023-04-25 03:13 UTC, jeongwusi commented on src/types/types.ts
> +export type SortingFilter = (typeof SORTING_FILTER)[number];
interface가 아닌 typeof을 통해 타입 추론을 하는 방식으로 하셨네용! 아주 대단합니다.

그러한 시도가 타입스크립트를 이해하는데 아주 큰 도움이 될 거라고 생각합니다. 

고생하셨어요~~