[점심 뭐 먹지 미션 Step 1] 룩소(우정균) 미션 제출합니다.
woowacourse/react-lunch pull request #7
Opened 2023-04-13 06:15 UTC by woo-jk

2023-04-14 17:01 UTC, jho2301 requested changes
안녕하세요 룩소~!
이번 미션에서 리뷰하게 된 파노라고 합니다. 만나서 반갑습니다 👍 

컴포넌트 구조에 있어서 고민을 많이 해주신 것 같은데 명확하게 파악할 수 있었어요 
현재 과제의 구조가 비교적 단순하긴해서 앞으로 복잡도가 높아져감에 따라 어떻게 구조를 가져갈 것인지 계속해서 고민해보면 좋겠습니다 

> 덩치 큰 App 컴포넌트
여러 컴포넌트에서 공유하는 상태가 있을 경우 컴포넌트들의 공통 상위 컴포넌트에 상태를 가지도록 했습니다. 하지만 컴포넌트 구조를 보면 알다시피 대부분의 컴포넌트의 상위 컴포넌트는 App 컴포넌트입니다. 그러다보니 App 컴포넌트에 많은 상태와 그 상태들을 다루는 함수들이 존재하게 되어 다른 컴포넌트들보다 크기가 커지는 문제가 발생했습니다. 또한 필요한 상태가 본인 컴포넌트에 위치하지 않고, 상위 컴포넌트에 위치하고 있다보니 상태의 흐름을 파악하기가 쉽지 않다고 느꼈습니다. 아직은 작은 애플리케이션이라 감당 가능한 수준이지만 앞으로 더 거대한 규모의 애플리케이션을 개발한다면 이런 문제가 더욱 커질 것이라고 생각합니다. 이러한 문제들은 리액트 컴포넌트의 고질적인 문제인지, 아니면 제가 아직 상태 관리에 미숙해서 그런 것인지 궁금합니다.

제 생각에는 App.tsx 파일의 코드가 80여라인이고, 그렇게 문제가 되는 복잡도는 아닌 것 같아요. 현재 프로그램의 목적이 하나이기 때문에 그렇게 문제가 되지않는다고 보는것인데, 물론 네이버메인페이지와 같은 다양한 목적을 가지는 화면을 개발한다면 문제가 될 수도 있을 것 같아요. 그때는 App파일이 점심뭐먹지 컴포넌트가 되면 될것 같아요.  컴포넌트의 prop을 어디까지 드러내야하는지, 어떤 데이터는 상태로 관리할 수 있을지 계속 비교해보면서 고민해보시면 될 것 같습니다. 고민을 하면서 전역상태를 생각하시고 있는지는 모르겠으나, 대개의 경우 전역상태가 그렇게 크게 필요하진 않을지도 몰라요. 

> 도메인 로직
레벨1까지는 UI와 도메인 로직을 철저히 분리했지만, 이번 미션에서는 도메인 로직들(RestaurantList 컴포넌트의 필터링 관련 로직 등)을 굳이 분리하지 않고 역할에 맞는 컴포넌트 내에서 위치하도록 했습니다. 이렇게 작성한 이유는 state를 사용함으로 인해 UI 로직과 도메인 로직의 경계선이 흐릿해졌다고 생각했고, 리액트의 컴포넌트는 단순 UI 로직이 아닌 그 이상의 역할을 한다고 생각했기 때문이었습니다. 이러한 생각이 맞는 생각인지, 아니면 제가 무언가 잘못 생각하고 있는지 궁금합니다. 또한 현업에서 개발할 때는 도메인 로직들을 컴포넌트에 위치하도록 하는지, 아니면 외부로 분리를 하는지도 궁금합니다.

요 프로그램에서 도메인이랄게 사실 이전의 과제들과 비교해서 크게 없는게 첫번째라고 생각하구요. 상태가 생김으로써 왜 흐려졌다고 생각하셨는지 궁금하네요! 상태의 위치와 관계없이 도메인로직은 분리할 수 있는 것 아닐까요? 저는 요기서 멍청한 컴포넌트(dumb component)라는 키워드에 대해서 찾아보셔도 좋을 것 같아요. 찾아보는 과정에서 나오는 패턴보다는 어떻게 컴포넌트를 구분하는지 관점에 대해서 학습해보시면 좋을 것 같습니다~!

2023-04-14 17:01 UTC, jho2301 commented on cypress/fixtures/mockData.json
> +    },
스키마에 대해서 타이핑 해보면 어떨까요??

2023-04-14 17:01 UTC, jho2301 commented on src/App.tsx
> +  };
Component 클래스에서 제네릭으로 받는 타입에 대해서 알아보셔도 좋을 것 같아요

2023-04-14 17:01 UTC, jho2301 commented on src/types/restaurant.ts
> +export type SortOption = "name" | "distance";
union과 enum에 대해서 비교해봐도 좋을 것 같아요

2023-04-14 17:01 UTC, jho2301 commented on src/App.tsx
> +      </div>
요렇게 객체리터럴을 선언하고 전개하는 이유가 무엇인가요? 개인적으로는 중복된 코드로 불필요해보여요

2023-04-14 17:01 UTC, jho2301 commented on src/App.tsx
> +        <RestaurantList {...restaurantListProps} />
요소의 순서에 따라 어떻게 요소가 z축에서 정렬되는지 확인해봐도 좋을 것 같습니다. 포인트는 모달이 Header, Filter, List보다 상단에 선언되어야하는지예요

2023-04-14 17:01 UTC, jho2301 commented on src/components/Filter/index.tsx
> +  }
value가 카테고리 옵션이라는 가정은 강제성이 없어 깨지기 쉬운것같아요. 파싱을 통해 타입을 좁혀보면 어떨까요? any -> CategoryOption

2023-04-14 17:01 UTC, jho2301 commented on src/App.tsx
> +    };
컴포넌트의 이벤트 관점에서 컴포넌트의 prop을 정의해보면 어떨까요?  필터 컴포넌트에서는 선택 이벤트가 일어나는 것이니, 이벤트를핸들링한다는 의미에서 onSelect - handleSelct 와 같은 네이밍이 된다면 더 자연스러울 것 같아요. 기존 요소들 input, textarea, button 등등 어떻게 동작을 전달하는 속성의 네이밍이 어떻게 되어있는지 비교해봐도 좋겠습니다

2023-04-14 17:01 UTC, jho2301 commented on src/components/RestaurantList/index.tsx
> +  }
comopnentDidUpdate는 컴포넌트당 하나 존재할 수밖에 없기때문에 동작이 위처럼 2개라면 추상화를 통해 복잡도를 낮춰봐도 좋을 것 같아요

2023-04-14 17:01 UTC, jho2301 commented on src/components/RestaurantList/index.tsx
> +    if (localStorageData) {
명시적으로 데이터가 있음을 나타내보면 어떨까요?

2023-04-14 17:01 UTC, jho2301 commented on src/components/RestaurantList/index.tsx
> +    const mockList: Restaurant[] = JSON.parse(JSON.stringify(mockData.restaurants));
어떻게 데이터를 가져오는지 알 필요는 없을 것 같아요. 컴포넌트에서 하고싶은것은 `데이터를 가져온다` 라는 내용만 알면 충분하지 않을까요?

2023-04-14 17:01 UTC, jho2301 commented on cypress/e2e/app.cy.ts
> +  });
농민백암순대 ~~ 같은 목데이터는 테스트에서 알아야할 내용은 아닌 것 같아요. 서비스 되는 제품이라면 음식점은 계속 추가될 것으로 예상해볼 수 있는데, 음식점들이 추가되는 상황에 이 테스트가 유효할지 고려해보면 좋을 것 같습니다.

2023-04-14 17:01 UTC, jho2301 commented on cypress/e2e/app.cy.ts
> +  });
조건값이 요 test suite에 명시적으로 설정될수 있으면 좋을 것 같아요. 모종의 이유로 mock데이터가 변경되면 영문도모르고 테스트가 깨질수있어요

2023-04-14 17:03 UTC, jho2301 approved these changes
아 요거 어프룹하고 스텝2에서 봅시당 ㅎㅎ

2023-04-14 17:03 UTC, merged

2023-04-16 11:03 UTC, woo-jk commented on cypress/fixtures/mockData.json
> +    },
스키마에 대해 공부해보고 restaurant의 스키마는 Restaurant 타입과 유사하게 설정할 수 있을 것 같아요.
```js
Restaurant {
  id: number;
  name: string;
  category: Category;
  distance: Distance;
  description?: string;
  link?: string;
}
```
다만, 이를 fixture에 적용하는 방법은 구글링을 해도 쉽게 찾을 수 없었는데요 ㅠ 적용 방법에 대해 간단한 힌트를 얻을 수 있을까요?

2023-04-16 11:16 UTC, woo-jk commented on src/App.tsx
> +  };
Component 클래스에서 state와 props의 타입을 제네릭으로 받으면 더 안정성있는 컴포넌트를 만들 수 있네요!

2023-04-16 11:24 UTC, woo-jk commented on src/App.tsx
> +      </div>
render() 함수의 return 문을 더 깔끔하게 만드려고 시도했으나, 이제보니 불필요한 로직 같네요..! 가독성도 오히려 떨어지는 것 같구요. 수정하겠습니다.

2023-04-16 11:24 UTC, woo-jk commented on src/App.tsx
> +        <RestaurantList {...restaurantListProps} />
넵 확인해보고 수정하겠습니다!

2023-04-16 11:25 UTC, woo-jk commented on src/types/restaurant.ts
> +export type SortOption = "name" | "distance";
enum은 기존에 안써봤는데 한 번 학습해보겠습니다.

2023-04-16 16:44 UTC, woo-jk commented on src/components/Filter/index.tsx
> +  }
파싱을 한다는 것이 타입 변환을 의미하는 걸까요?

2023-04-16 16:45 UTC, woo-jk commented on src/App.tsx
> +    };
넵 네이밍을 조금 더 신경쓰겠습니다!

2023-04-16 17:12 UTC, woo-jk commented on src/components/RestaurantList/index.tsx
> +    const mockList: Restaurant[] = JSON.parse(JSON.stringify(mockData.restaurants));
넵 조금 더 추상화해보겠습니다!

2023-04-16 17:13 UTC, woo-jk commented on cypress/e2e/app.cy.ts
> +  });
fixture를 사용하여 테스트 하는 경우에도 그런 상황을 신경 써주는 것이 더 나은 테스트일까요!?

2023-04-16 17:17 UTC, woo-jk commented on cypress/e2e/app.cy.ts
> +  });
파노가 말씀해주신 mock데이터는 실제 애플리케이션에서 사용되는 mock데이터인가요? 테스트 fixture에 있는 mock데이터인가요? 
저는 두가지 경우에 서로 분리된 mock데이터를 사용하고 있습니다!

2023-04-18 16:35 UTC, jho2301 commented on cypress/fixtures/mockData.json
> +    },
그냥 ts파일로 관리해도좋을것같아요!

2023-04-18 16:35 UTC, jho2301 commented on cypress/fixtures/mockData.json
> +    },
@woo-jk  알람용

2023-04-18 16:39 UTC, jho2301 commented on src/components/Filter/index.tsx
> +  }
value가 어떤 값인지 알지못하는 형태의 데이터이니 검증을 통해 CategoryOption타입으로 확정할수있는 과정이 있다면 좋을 것 같아요

2023-04-18 16:42 UTC, jho2301 commented on cypress/e2e/app.cy.ts
> +  });
fixture도 외부의 모듈인데 테스트가 fixture에 대해 알고있는게 긍정적으로 보이지는 않는것같아요. fixture가 있기때문에  괜찮다고 생각하시나요? 룩소의 의견이 있다면 근거를 제시해주시면 더 재밌게 얘기해볼 수 있을것같아요!

2023-04-18 16:43 UTC, jho2301 commented on cypress/e2e/app.cy.ts
> +  });
fixture를 뜻하는 것이었습니답. 요거는 테스트에 대해 이야기를 하고있는 맥락이기에 후자가 나오기에는 적절하지 않은 상황같아요