[점심 뭐 먹지 미션 Step 2] 제레미(김민석) 미션 제출합니다.
woowacourse/react-lunch pull request #76
Opened 2023-04-17 04:55 UTC by shackstack

useContext를 활용하여 전역 상태에 접근할 수 있도록 코드를 수정하였습니다.

2023-04-17 14:32 UTC, InSeong-So commented
리뷰 요청이 안 왔네요🥲

2023-04-17 14:57 UTC, InSeong-So requested changes
안녕하세요🤗 빠르게 돌아왔군요! 레벨2 진행하느라 고생 많으셨습니다.
함수형으로 수정하고 lint도 다시 적용했네요!

우선 중복된 문제점이 여러 개 보이네요🥲 전반적으로 함수 컴포넌트로 잘 변환해주셨어요. 렌더링 최적화(메모이제이션 등)나 Context API의 활용을 이펙티브하게 가져가면 좀 더 좋은 성능을 보일 것 같아요!

리액트를 갑자기 접하게 되면서 많은 러닝커브가 있을 것이라 생각돼요. 천천히 공식 문서를 찾아보면서 리액트의 개발자 도구를 잘 활용해보는 시간을 가지면 좋겠습니다🪄

제레미가 이해가 잘 되지 않거나 벽에 부딪히는 상황이 온다면 꼭 코멘트로 남겨주시거나, 디엠을 부탁드려요. 현재 코드에서는 App.tsx에서 Context API를 분리하는 것을 최우선적으로 작업해보는 것을 추천드립니다.

2023-04-17 14:57 UTC, InSeong-So commented on src/components/Header.tsx
> +  return (
변경될 여지가 많이 없는 컴포넌트네요! Title이 변경될 수 있는 상황이 존재할 수 있으니 props로 할당받는 것은 어떨까요?
또한 불필요한 렌더링이 발생할 수 있으므로 메모이제이션을 활용해보는 것은 어떨까요?

2023-04-17 14:57 UTC, InSeong-So commented on src/components/Modal.tsx
> +  closeModal: Function;
Function 타입은 상위 타입이므로 가급적 사용을 지양해주세요🙃

2023-04-17 14:57 UTC, InSeong-So commented on src/components/Modal.tsx
> +      <ModalBackDrop onClick={() => props.closeModal()}></ModalBackDrop>
인라인 함수 지양해주세요!

```suggestion
<ModalBackDrop onClick={props.closeModal}></ModalBackDrop>
```

2023-04-17 14:57 UTC, InSeong-So commented on src/App.tsx
> +});
이렇게 사용하는 경우 각 컴포넌트 파일에 상호참조 관계가 발생할 수 있습니다. App에서 컴포넌트를 import하는데, 컴포넌트는 App에서 context를 import 하기 때문이에요. 별도 분리하는 것을 추천드립니다.

또한 초깃값을 상수화시켜서 알기 쉽게 분리해주는 게 좋아요!
+ state, setState라는 네이밍은 프레임워크가 약속한 규약과 어느정도 상충되므로 다른 네이밍을 채택하면 좋겠네요😊

2023-04-17 14:57 UTC, InSeong-So commented on src/App.tsx
>          <SelectContainer>
이렇게 Context API를 사용하는 것은 큰 안티 패턴입니다.
state가 변경될 때마다 하위 컴포넌트가 전체적으로 재렌더링 되기 때문이에요.
초기 Context API가 문제 되었던 이유는 상기 이슈 때문이었고, 이를 해결하는 여러 방법들이 나왔으니 꼭 기억하시면 좋겠습니다.

[참조](https://junjangsee.tistory.com/entry/React-Context-API-useReducer-%EC%A1%B0%ED%95%A9-%EC%82%B4%ED%8E%B4%EB%B3%B4%EA%B8%B0-featTypescript)

2023-04-17 14:57 UTC, InSeong-So commented on src/types/Restaurant.tsx
> +  [key: string]: any;
이 코드가 있는 이유가...?!

2023-04-17 14:57 UTC, InSeong-So commented on src/components/SelectBox.tsx
> +    <Select name="" onChange={(event) => updateRestaurants(event.target.value)}>
name이 공백이라면 제거해도 되는 속성 같네요!

```suggestion
    <Select name="" onChange={updateRestaurants}>
```

이렇게 선언하고 `updateRestaurants` 함수에 메모이제이션을 적용하면 어떨까요?

2023-04-17 14:57 UTC, InSeong-So commented on src/components/SelectBox.tsx
> +          .sort((a, b) => (a[value] > b[value] ? 1 : -1)),
이 코드는 유틸 함수로 분리해도 좋을 것 같아요. 혹은 해당 파일에 컴포넌트 바깥으로 선언하면 어떨까요?

2023-04-18 01:35 UTC, shackstack commented
> 리뷰 요청이 안 왔네요🥲

헉... 리뷰요청을 안했었네요ㅠㅠ 그럼에도 피드백주셔서 감사합니다.
수정하고 다시 리뷰요청드리겠습니다!

2023-04-18 14:29 UTC, shackstack commented on src/components/Modal.tsx
> +  closeModal: Function;
타입스크립트 어렵네요... 수정해보겠습니다!

2023-04-18 14:38 UTC, shackstack commented on src/components/Modal.tsx
> +      <ModalBackDrop onClick={() => props.closeModal()}></ModalBackDrop>
혹시 지양해야하는 이유가 가독성 때문일까요?

2023-04-19 08:32 UTC, shackstack commented on src/App.tsx
> +});
좋습니다! 이 경우 modalinfo, sortBy, categorizeBy의 초깃값만 분리하면 되겠죠?

2023-04-19 08:33 UTC, shackstack commented on src/App.tsx
>          <SelectContainer>
처음 적용하다보니 안티패턴이 많이 발생하네요ㅠ 더 공부해보도록 하겠습니다.

2023-04-19 08:33 UTC, shackstack commented on src/types/Restaurant.tsx
> +  [key: string]: any;
gpt 무지성 수용의 폐해인것 같습니다 ㅠ

2023-04-19 08:37 UTC, shackstack commented
파랑 피드백 반영이 늦어서 죄송해요ㅠ 다음 미션을 밤새가며 진행하느라 수정할 시간이 많이 부족했습니다! 피드백 주신대로 수정을 해보았는데 아직 모르는 부분이 많아 의도하신 방향대로 수정된건진 잘 모르겠네요. 여러모로 고생많으십니다.

2023-04-21 01:23 UTC, InSeong-So approved these changes
에고, 예비군 일정으로 인해 많이 늦어졌네요😭
피드백 반영을 위해 메모이제이션을 적용하고자 공부한 부분이 좋네요. 고생 많으셨어요!

우선... 제레미 코드 일부분에서 GPT의 향이 강하게 납니다😂
템플릿 정도와 방법론만 의지하고, 지금은 공부 우선이니까 지식을 많이 습득하길 빌어요!

크게 고칠 부분 없이 많이 개선해주셨네요.
몇 가지 코멘트를 남겨놓았어요. 확인만 해주시고 다음 미션도 파이팅입니다!👏

2023-04-21 01:23 UTC, InSeong-So commented on src/App.tsx
> +  );
이 두 코드는 App 컴포넌트 바깥에 분리하는 게 좋아보여요! 의존하는 값이 없네요🤗

2023-04-21 01:23 UTC, InSeong-So commented on src/components/Header.tsx
> +  );
오.......... 제가 의도한 부분은 Header 컴포넌트에 React.memo를 적용하는 것이었습니다! props의 변경에 따른 재렌더링만 일어나면 되는 부분이었기 때문에요!

2023-04-21 01:23 UTC, InSeong-So commented on src/components/Modal.tsx
> +  };
이렇게 분리된 코드는 useCallback 함수로 메모이제이션하면 매번 함수를 생성하는 연산을 스킵할 수 있습니다!

2023-04-21 01:23 UTC, InSeong-So commented on src/components/RestaurantList.tsx
> +        )
이 코드만 useMemo를 사용해서 변수로 분리해두고, 해당 값을 *.map으로 리스트를 출력하면 어떨까요!?

2023-04-21 01:23 UTC, InSeong-So commented on src/components/SelectBox.tsx
>  export default SelectBox;
SelectBox의 경우도 여러 곳에서 사용될 수 있는 원자 단위 컴포넌트고, 하위 계층에 존재할 수 있기 때문에 많은 재렌더링의 요지가 있어요. 이런 컴포넌트는 React.memo 처리해두면 좋습니다!

2023-04-21 01:23 UTC, merged