[점심 뭐 먹지 미션 Step 2] 우스(김영길) 미션 제출합니다.
woowacourse/react-lunch pull request #77
Opened 2023-04-17 04:55 UTC by Gilpop8663

안녕하세요 브콜! 스탭2를 마치고 또 다시 PR을 드립니다 😀

## 사이트 바로가기
### <a href="https://gilpop8663.github.io/react-lunch/" alt="점심 뭐 먹지">점심 뭐 먹지</a>

스탭2를 진행하며 신경 쓴 부분들을 적어보았습니다.

## Custom Hooks을 이용하여 재사용 가능한 기능을 분리한다.

- useLocalStorage hook을 만들었습니다. 로컬 스토리지에 키값, 초기값을 넣어 로컬 스토리지에 저장된 값이 있다면 불러오고, 그렇지 않다면 초기 값을 설정하는 훅은 만들었습니다. 음식점 목록 이외에도 사용할 수 있을 것 같았습니다.

- useModalState hook을 만들었습니다. 모달 창이 열릴 때 스크롤 방지하는 로직이 있었는 데 여러 개의 모달을 만든다면 일일이 설정해줘야하기에 로직을 분리해서 훅으로 만들어주었습니다.

- useSafeUnionTypeState hook을 만들었습니다.  유니온 타입을 가진 state가 있었고, 그 state에 event.currentTarget.value을 넣어줘야 하는데 string 값이여서 타입 에러가 났습니다. 해결 방법으로 유니온 안의 내용들로 구성된 배열을 이용해 타입 에러를 없앴습니다. 이러한 유니온 타입을 이용할 때 마다 다르게 설정해야 하는 것을 훅으로 만들어 재사용하도록 해보았습니다.

## Class Component를 Function Component로 마이그레이션 한다.

- componentDidMount , componentDidUpdate, componentWillUnmount를 useEffect로 변경했습니다.

- state를 useState로 변경했습니다.

리뷰해주셔서 감사합니다 🔥🔥

2023-04-17 16:57 UTC, Tanney-102 requested changes
안녕하세요 우스!
함수형 컴포넌트로 깔끔하게 마이그레이션 해주셨네요👍
여러 커스텀 훅을 시도하신 것도 인상 깊었습니다.
구현해주신 훅 위주로 리뷰 드렸으니 간단하게만 확인해주세요~
모두 반영하지 않으셔도 좋습니다.
코멘트 드린 것만 한 번씩 확인하시고 다시 리뷰요청 주시면 바로 머지하겠습니다! (다음 미션을 위해!)

2023-04-17 16:57 UTC, Tanney-102 commented on src/hooks/useSafeUnionTypeState.ts
> +    if (typeof text !== 'string') return false;
여기서 예외처리를 할거라면 차라리 text를 string타입으로 받는 게 낫지 않을까요?

2023-04-17 16:57 UTC, Tanney-102 commented on src/hooks/useSafeUnionTypeState.ts
좋은 아이디어네요👍
시간 날 때 런타임에서 분기하는 방식 말고 타입만으로 해결볼 수는 없을지도 고민해보시면 좋겠습니다!

2023-04-17 16:57 UTC, Tanney-102 commented on src/hooks/useModalState.ts
> +    document.body.dataset.hideScroll = 'true';
```suggestion
    document.body.dataset.hideScroll = newValue === null
      ? 'false'
      : 'true'
```

2023-04-17 16:57 UTC, Tanney-102 commented on src/hooks/useModalState.ts
> +export const useModalState = <Type>(
훅 내용만 봐서는 modal과 관련있는 훅인지 잘 모르겠습니다.
바뀌는 상태에 따라 hideScroll 여부를 결정한다는 뜻을 이름에 녹여보면 어떨까 싶어요.

추가로 조금 더 추상적인 훅 구현을 제안드려봅니다.
```ts
const useModalState = <T>(initialState: T, predicate: (state: T) => boolean) => {
  ...
  const setValue = (newValue: T) => {
    document.body.dataset.hideScroll = predicate(newValue) ? 'true' : 'false'
    setState(newValue)
  }
}

// 사용처
useModalState(
  someValue, 
  (state) => state !== null,
)
```

요렇게 하면 hideScroll을 하는 로직은 훅에 위임하면서 그 기준은 사용처마다 다르게 지정할 수 있어 재사용에 유리합니다.
그냥 제 취향에 따라 드리는 제안이니 고려만 해보시면 좋겠습니다

2023-04-17 16:57 UTC, Tanney-102 commented on src/hooks/useLocalStorage.ts
> +
이 훅은 호출될때마다 매번 localStorage에 접근하는군요🤔

2023-04-18 02:22 UTC, Gilpop8663 commented on src/hooks/useLocalStorage.ts
> +
리액트에서 리렌더되면 App에 있는 모든 훅, 코드들이 실행되는 것을 새롭게 알게 되었습니다.  처음에 useLocalStorage를 선언해서 사용하면 내부 코드가 한 번만 실행되는 줄 알았네요! 알려주셔서 감사합니다 브콜! 👍👍👍

코드는 다음과 같이 고쳐보았습니다 

```ts
import { useEffect, useState } from 'react';
import {
  getSavedLocalStorageList,
  hasSavedLocalStorageList,
  saveLocalStorageList,
} from '../domain/initializeRestaurantList';

export const useLocalStorage = <Type>(
  key: string,
  initializeValue: Type,
): [value: Type, setValue: (newValue: Type) => void] => {
  const [value, setState] = useState(initializeValue);

  const setValue = (newValue: Type) => {
    setState(newValue);
    saveLocalStorageList<Type>(key, newValue);
  };

  useEffect(() => {
    const getSavedList = getSavedLocalStorageList(key);

    if (!hasSavedLocalStorageList(key)) {
      setValue(initializeValue);
      return;
    }

    setState(getSavedList);
  }, []);

  return [value, setValue];
};

```

2023-04-18 02:22 UTC, Gilpop8663 commented on src/hooks/useModalState.ts
> +export const useModalState = <Type>(
브콜의 제안대로 코드를 고쳐보니 코드 가독성과 다른 컴포넌트에서 재사용할 수 있다는 점이 확연히 보여서 브콜의 생각에 동의하게 되었습니다. 👍👍👍👍👍👍 최고! null값을 hook에서 뺄 수 있어서 좋았어요 

```ts
import { useState } from 'react';

export const useHideScrollState = <Type>(
  initializeValue: Type,
  predicate: (state: Type) => boolean,
): [value: Type, setValue: (newValue: Type) => void] => {
  const [value, setState] = useState(initializeValue);

  const setValue = (newValue: Type) => {
    document.body.dataset.hideScroll = predicate(newValue) ? 'true' : 'false';
    setState(newValue);
  };

  return [value, setValue];
};

```

2023-04-18 02:22 UTC, Gilpop8663 commented on src/hooks/useSafeUnionTypeState.ts
> +    if (typeof text !== 'string') return false;
브콜의 생각에 동의해서 고쳐보았습니다~ 다만 고치는 과정속에서 <Type extends string>이 추가 되었는 데 올바른 방향인지 궁금합니다!


```ts
import { useState } from 'react';

export const useSafeUnionTypeState = <Type extends string>(
  initializeValue: Type,
  typeOfArray: string[],
): [value: Type, setValue: (text: string) => void] => {
  const [value, setState] = useState(initializeValue);

  const isInCludes = (text: string): text is Type => {
    return typeOfArray.includes(text);
  };

  const setValue = (text: string) => {
    if (!isInCludes(text)) return;

    setState(text);
  };

  return [value, setValue];
};

```

2023-04-18 02:22 UTC, Gilpop8663 commented on src/hooks/useSafeUnionTypeState.ts
런타임에서 분기하는 방식이  `if(isInCludes(text)) return;` 이 부분을 말하시는 걸까요? 제가 제대로 이해한 것이 맞는지 궁금합니다 🔥


```ts
  const setValue = (text: string) => {
    if (!isInCludes(text)) return;

    setState(text);
  };
```

2023-04-19 01:49 UTC, Tanney-102 commented on src/hooks/useSafeUnionTypeState.ts
> +    if (typeof text !== 'string') return false;
의도한대로 잘 바꿔주셨네요👍

2023-04-19 01:50 UTC, Tanney-102 commented on src/hooks/useSafeUnionTypeState.ts
네네 맞아요!
지금과 같은 방식도 크게 문제는 없습니다

2023-04-19 01:52 UTC, Tanney-102 approved these changes
안녕하세요 우스!
제가 의도했던 내용을 잘 파악하시고 반영해주셨네요👍👍
이번 미션은 이만 머지하도록 하겠습니다 고생많으셨어요!

2023-04-19 01:52 UTC, merged

2023-04-25 03:07 UTC, WaiNaat reviewed
혹시 components 폴더 안에서 또 컴포넌트별 폴더를 만들어서 분리하시는건 어떻게 생각하시나요?

2023-04-25 03:07 UTC, WaiNaat commented on src/hooks/useSafeUnionTypeState.ts
> +export const useSafeUnionTypeState = <Type extends string>(
타입가드 함수를 만들어서 setState 이전에 처리하는 방식도 있을 것 같은데 이 부분까지 새로운 훅으로 만든 이유가 있을까요?

2023-04-25 03:07 UTC, WaiNaat commented on src/domain/initializeRestaurantList.ts
> +export const getSavedLocalStorageList = (key: string) => {
이 부분은 이제 도메인과는 큰 연관성이 없어서 따로 util같은 쪽으로 분리해도 좋을 것 같아요!

2023-04-25 03:07 UTC, WaiNaat commented on src/types/restaurantInfo.ts
> +export type FoodCategory = '전체' | '일식' | '한식' | '중식' | '아시안' | '양식' | '기타';
constants에 저장했던 배열을 이용해서 타입을 만들면 좋을 것 같아요!