[점심 뭐 먹지 미션 Step 2] 아커(전증훈) 미션 제출합니다.
woowacourse/react-lunch pull request #97
Opened 2023-04-17 08:58 UTC by jeonjeunghoon

[점심 뭐 먹지](https://jeonjeunghoon.github.io/react-lunch/)

브콜 안녕하세요!

Step2에서 또 다시 뵈어 기쁩니다~

이번 미션은 Functional Component로 마이그레이션을 진행하며 Custom Hook을 조금 알아가봤습니다.

함수형 컴포넌트로 변경하는 일은 어렵지 않았지만, Hook을 작성하는 일이 많이 버거웠네요 ㅠㅠ

이번 미션 리뷰도 잘 부탁드립니다!

## 🙋‍♂️ 질문

1. 리액트에서는 직접 DOM 조작을 피하라고 권장하는데, 어디까지가 직접적인 DOM 조작인지 모르겠습니다.
`classList.add` 와 같은 메서드부터 `contains` 와 같이 클래스가 존재하는지 확인하는 작업까지 직접적인 DOM 조작인지 헷갈립니다. 혹시 `document` 객체를 사용하는 것 자체가 직접적인 DOM 조작일까요?
이것과 관련된 학습 키워드 추천 부탁드립니다!
2. ReactNodeList를 반환하는 함수는 무조건 Custom Hook을 통해 재사용성을 고려해야 할까요?
제 생각은 이후에 다른 컴포넌트에서 사용될 일이 있다면, 그때 분리를 고민하면 된다고 생각합니다.
따라서 하나의 컴포넌트에서만 사용되는 ReactNodeList는 컴포넌트 내부에 두었습니다.
3. 각 컴포넌트 내부에서 event를 핸들링하는 함수들을 Custom Hook으로 분리해야 할까요?
현재 이벤트 핸들링이 필요한 컴포넌트는 Main, Modal, Select입니다.
Main은 beforeunload 이벤트를 처리하기 위함이고,
Select는 카테고리 및 정렬 선택 이벤트를 처리하기 위함이고,
Modal은 모달 닫기 이벤트를 처리하기 위함입니다.
모달 닫기 이벤트와 같은 경우는 재사용될 일이 있을 것같아 분리하면 좋을 것같다는 생각이 듭니다.
혹시 이것도 2번 질문과 같이 재사용이 필요해지면 그때가서 분리를 고민해야 할까요?
현재는 Custom Hook 작성이 익숙치 않을 뿐더러, 분리의 필요성이 긴가민가하여 컴포넌트 내부에 이벤트 핸들러가 작성되어 있습니다.

2023-04-17 17:24 UTC, Tanney-102 requested changes
안녕하세요 아커~
깔끔하게 마이그레이션을 잘 해주셨네요👍
구현하신 훅 위주로 간단히 리뷰드렸어요!
모두 반영할 필요는 없으니 간단하게만 확인하시고 다시 리뷰요청 주셔요!

질문에 답변드립니다.
1. 선언적 프로그래밍에 대해 찾아보시면 도움이 되실 것 같습니다. 리액트에서 JSX나 표현식을 통해 선언적으로 view를 서술하기 때문에 명령형으로 dom을 조작(직접 innerHTML을 변경한다든지, classList를 메뉴얼하게 add/remove 하는 일 등)하는 것과 어울리지 않습니다. 주어진 상태에 따라 어떤 view가 그려져야 하는지만 잘 신경쓰면 사실 크게 dom을 조작할 일이 많지는 않아요! 물론 focus 등과 같이 어쩔 수 없이 직접 dom에 접근해야하는 일이 종종 생기긴합니다!

2. 코멘트 드리긴 했는데 사실 ReactNodeList만을 반환한다면 컴포넌트 안에 직접 서술하거나 혹은 분리를 하더라도 일반함수나 컴포넌트로 분리하는 게 낫다고 생각합니다. 커스텀 훅을 사용하면 컴포넌트 로직을 분리하기에 용이하지만 모든 게 훅으로 분리될 필요는 없습니다.

3. 필요성을 느끼지 못한다면 반드시 분리할 필요는 없다고 생각해요. 지금 미션보다는 이후 미션에서 조금 더 규모가 큰 컴포넌트를 다루며 언제 훅으로 분리하면 좋을지 직접 느껴보시면 좋겠습니다!

2023-04-17 17:24 UTC, Tanney-102 commented on src/hooks/filterSection.ts
> +    };
`...currentOption` 요거는 빠져도 될 것 같습니다!

2023-04-17 17:24 UTC, Tanney-102 commented on src/hooks/modal.ts
> +export const useModal = (setSelectedRestaurant: CallableFunction) => {
추상적인 이름(useModal)에 비해 상당히 구체적인 인자(setSelectedRestaurnat)을 받는군요🤔

2023-04-17 17:24 UTC, Tanney-102 commented on src/hooks/restaurantItem.ts
> +};
이 훅은 어떤 역할을 하나요?
사용처에서 그냥 setSelectedRestaurant를 직접사용하는 것과 어떤 차이가 있나요?

2023-04-17 17:24 UTC, Tanney-102 commented on src/hooks/restaurantList.tsx
> +};
훅으로 구현할 이유가 없어보입니다. 그냥 함수나 컴포넌트로 작성했어도 충분했을 것 같아요

2023-04-18 13:44 UTC, jeonjeunghoon commented on src/hooks/filterSection.ts
> +    };
이 부분은 잘 모르겠습니다 ㅜㅜ
말씀해주신 대로 `...currentOption` 을 지우고 실행해봤는데, `updatedOption` 에 값이 제대로 저장되지 않네요...
아마 원인은 `updatedOption` 은 두 쌍의 키값을 갖고 있어야 하는데, `selectedOption` 은 한 쌍의 키값을 갖고 있어서 문제가 되는 것같습니다!

2023-04-18 13:44 UTC, jeonjeunghoon commented on src/hooks/modal.ts
> +export const useModal = (setSelectedRestaurant: CallableFunction) => {
다시 보니 그렇네요!

2023-04-18 13:47 UTC, jeonjeunghoon commented on src/hooks/restaurantItem.ts
> +};
고민했던 부분입니다!
`setSelectedRestaurant()` 보다는 좀 더 선언적으로 작성하고 싶어 `selectRestaurant` 라는 함수로 추상화하기 위해 훅을 작성했습니다.
혹시 별반 차이 없을까요?

2023-04-18 13:49 UTC, jeonjeunghoon commented on src/hooks/restaurantList.tsx
> +};
커스텀 훅에 대해 조금 공부해보니 제가 작성한 코드는 훅으로 작성될 이유가 없었던 것같습니다.
그래서 이런 식으로 분리해둔 `restaurantList` 나 `select` 에서 사용되는 자식 컴포넌트 렌더링 함수들은 다시 해당 컴포넌트 내부에 작성했습니다!

2023-04-18 14:04 UTC, jeonjeunghoon commented
브콜 안녕하세요! 😁
피드백 주신 부분 위주로 고민하고 수정해봤습니다.
아직 React는 물론이고 JavaScript, TypeScript도 부족한 상황이라 쉽지 않은 미션이었네요 ㅎㅎ…

이전에 충돌 이슈 때문에 리뷰 요청이 늦었음에도 불구하고 피드백 해주셔서 너무 좋았습니다.
소중한 피드백 정말 감사드립니다! 😆

### 🙋‍♂️ 질문

1. 여전히 JavaScript와 TypeScript 실력이 부족하다고 느끼고 있습니다. 그런 상황에서 React를 마주하니 조금 숨이 막히는 느낌인데, 어떤 방식으로 학습을 해나가야할지 고민입니다.
현재 ‘코어자바스크립트’ 를 읽으며 학습 중입니다. 이후에 바로 타입스크립트 혹은 리액트를 집중적으로 학습하는게 좋을 지, 혹은 딥다이브와 같은 책으로 자바스크립트를 더욱 깊게 학습할지 고민됩니다.

2023-04-19 01:56 UTC, Tanney-102 commented on src/hooks/restaurantItem.ts
> +};
의도가 귱금했습니다
일정한 기준대로 작성해주신거라면 괜찮은 것 같습니다👍

2023-04-19 01:57 UTC, Tanney-102 commented on src/hooks/filterSection.ts
> +    };
아하 타입이 다른가 보군요!
이해했습니다👍

2023-04-19 02:16 UTC, Tanney-102 approved these changes
안녕하세요 아커!
학습에 대해 고민이 많으시군요.
리액트 같은 친구들을 볼 때 숨이 턱턱 막히는 건 자연스러운 일인 것 같습니다~
단지 리액트라서가 아니라 덩치도 크고 (처음 사용해본다면) 생소한 라이브러리라는 점에서요.
리액트와 자바스크립트 사이 학습의 우선순위는 항상 어려운 문제입니다만 개인적으로는 언어 차원에서 일정수준 이상의 숙련도를 쌓는게 우선이라고 생각해요. 리액트 문서를 볼때 이게 리액트가 아니라 자바스크립트로 보이는가,라이브러리 api 명세를 볼때 대강 어떻게 돌아가겠거니가 상상이 되는가 정도를 기준으로 스스로 평가해보시면 좋겠습니다.

물론 이 내용들은 단순히 언어 vs 라이브러리 차원에서만 이야기 드린 것이구요! 개인적인 의견이니 참고만해주세요~ 더 궁금한 점 있으시면 편히 연락주셔요. 그럼 이번 미션은 요렇게 마무리 하시죠!

2023-04-19 02:16 UTC, merged